### ISSUE TITLE
EOFError instead of Token prompt when used with amazon-ecr-credential-helper

### ISSUE THREAD

**Issue by dizeee** [godaddy/aws-okta-processor#23]
We are using [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper) to pull Docker images from AWS ECR. It works fine when the session is already established, but initial authentication fails.

So this works fine:
```
# Remove any cached sessions
rm -rf ~/.aws/boto/cache ~/.aws-okta-processor/cache

# Run any AWS command (also works with Ansible, Terraform, etc)
AWS_PROFILE=my-profile aws sts get-caller-identity

# Enter Okta password

# Enter Okta token

# Pull image from ECR
AWS_SDK_LOAD_CONFIG=true AWS_PROFILE=my-profile docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPOSITORY_NAME}:${IMAGE_TAG}
```

But this does not:
```
# Remove any cached sessions
rm -rf ~/.aws/boto/cache ~/.aws-okta-processor/cache

# Pull image from ECR
AWS_SDK_LOAD_CONFIG=true AWS_PROFILE=my-profile docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPOSITORY_NAME}:${IMAGE_TAG}

# Enter Okta password
```

After entering Okta password we get the following error:
```
Password:
Info: Calling https://company-name.okta.com/api/v1/authn
Token: Traceback (most recent call last):
  File "/usr/local/bin/aws-okta-processor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/cli.py", line 74, in main
    command.run()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/commands/authenticate.py", line 74, in run
    credentials = self.authenticate()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/commands/authenticate.py", line 68, in authenticate
    credentials = saml_fetcher.fetch_credentials()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/fetcher.py", line 38, in fetch_credentials
    credentials = super(SAMLFetcher, self).fetch_credentials()
  File "/Users/dizeee/Library/Python/3.7/lib/python/site-packages/botocore/credentials.py", line 629, in fetch_credentials
    return self._get_cached_credentials()
  File "/Users/dizeee/Library/Python/3.7/lib/python/site-packages/botocore/credentials.py", line 639, in _get_cached_credentials
    response = self._get_credentials()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/fetcher.py", line 62, in _get_credentials
    no_okta_cache=self._configuration["AWS_OKTA_NO_OKTA_CACHE"]
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 76, in __init__
    user_pass=user_pass
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 146, in get_okta_single_use_token
    return self.handle_factor(response_json=response_json)
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 162, in handle_factor
    return self.verify_factor(factor=factor, state_token=state_token)
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 171, in verify_factor
    json_payload = factor.payload()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 409, in payload
    return {"passCode": input()}
EOFError: EOF when reading a line
Password:
```
It prompts the password again and after entering it for the second time it throws the same error and dies:
```
Info: Calling https://company-name.okta.com/api/v1/authn
Token: Traceback (most recent call last):
  File "/usr/local/bin/aws-okta-processor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/cli.py", line 74, in main
    command.run()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/commands/authenticate.py", line 74, in run
    credentials = self.authenticate()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/commands/authenticate.py", line 68, in authenticate
    credentials = saml_fetcher.fetch_credentials()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/fetcher.py", line 38, in fetch_credentials
    credentials = super(SAMLFetcher, self).fetch_credentials()
  File "/Users/dizeee/Library/Python/3.7/lib/python/site-packages/botocore/credentials.py", line 629, in fetch_credentials
    return self._get_cached_credentials()
  File "/Users/dizeee/Library/Python/3.7/lib/python/site-packages/botocore/credentials.py", line 639, in _get_cached_credentials
    response = self._get_credentials()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/fetcher.py", line 62, in _get_credentials
    no_okta_cache=self._configuration["AWS_OKTA_NO_OKTA_CACHE"]
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 76, in __init__
    user_pass=user_pass
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 146, in get_okta_single_use_token
    return self.handle_factor(response_json=response_json)
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 162, in handle_factor
    return self.verify_factor(factor=factor, state_token=state_token)
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 171, in verify_factor
    json_payload = factor.payload()
  File "/usr/local/lib/python3.7/site-packages/aws_okta_processor/core/okta.py", line 409, in payload
    return {"passCode": input()}
EOFError: EOF when reading a line
Error response from daemon: Get https://912850810755.dkr.ecr.eu-central-1.amazonaws.com/v2/php/manifests/7.4-dev-latest: no basic auth credentials
```

**Comment by tahoward** [comment]
Thanks for opening this issue. Unfortunately there isn't anything that can be done on this code base to fix the issue. I have a few projects built with aws-go-sdk and `input()` works fine.

If I call `docker-credential-ecr-login list` directly I am prompted for the Token without issues. This leads me to believe stdin pipe is not being passed to `docker-credential-ecr-login` when docker executes it.

You'll want to open an issue with docker regarding this.

As a work around I'd recommend using AWS CLI [get-login-password](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecr/get-login-password.html) instead.

**Comment by dizeee** [comment]
@tahoward Thanks for looking into this. `get-login-password` won't help much, as it basically just adds an extra authentication method for docker, while we still need to authenticate with Okta to execute `get-login-password`, so it's actually a bit simpler to use some lightweight AWS command like `aws sts get-caller-identity` to create session cache and then use it for docker. Anyway, thanks for your feedback, I'll try to open an issue for docker. Do you mind if I'll leave this one open for a while until I get to the bottom of this?

**Comment by tahoward** [comment]
Yes, feel free to leave this open.
